#lang planet neil/sicp
(define (accumulate combiner null-value term a next b)
  (if (> a b)
      null-value
      (combiner (term a)
         (accumulate combiner null-value term (next a) next b))))
(define (accumulate2 combiner null-value term a next b)
  (define (iter a result)
    (if (> a b)
        result
        (iter (next a) (combiner (term a) result))))
  (iter a null-value))
(define (sum term a next b)
  (define (plus a b) (+ a b))
  (accumulate plus 0 term a next b))
(define (product term a next b)
  (define (multiply a b) (* a b))
  (accumulate multiply 1 term a next b)
;  (accumulate2 multiply 1 term a next b)
  )

(define (inc n) (+ n 1))
(define (identity x) x)
(define (factorial n)
  (product identity 1 inc n))
;(factorial 6)

(define (pi n)
  (define (square x) (* x x))
  (define (inc n) (+ n 1))
  (define (term k)
    (if (even? k)
        (/ k (+ k 1))
        (/ (+ k 1) k)))
  (* 4.0 (product term 2 inc n))
; (* 4.0 (product2 term 2 inc n))
  )
(pi 10000)