#lang planet neil/sicp
(define (sqrt-iter guess x)
  (define improved (improve guess x))
  (if (good-enough? guess improved)
      guess
      (sqrt-iter improved x)))
(define (improve guess x)
  (average guess (/ x guess)))
(define (average x y)
  (/ (+ x y) 2))
(define (square x)
  (* x x))
(define (good-enough? guess improved)
  (< (abs(- guess improved)) 0.001))
(define (sqrt x)
  (sqrt-iter 1.0 x))
(sqrt 0.001)